// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardNeedsAttention = `-- name: DashboardNeedsAttention :many
(
  SELECT 'waitlist_stale'::text AS kind,
         w.id            AS ref_id,
         'waitlist'::text AS ref_kind,
         w.email         AS subject,
         COALESCE(w.interested_in, '') AS detail_hint,
         w.created_at    AS due_at
  FROM waitlist_entries w
  WHERE w.contacted_at IS NULL
    AND w.created_at < NOW() - INTERVAL '7 days'
)
UNION ALL
(
  SELECT 'hold_stale'::text AS kind,
         g.id         AS ref_id,
         'gecko'::text AS ref_kind,
         COALESCE(g.name, g.code) AS subject,
         g.code       AS detail_hint,
         g.updated_at AS due_at
  FROM geckos g
  WHERE g.status = 'HOLD'
    AND g.updated_at < NOW() - INTERVAL '7 days'
)
ORDER BY due_at ASC
LIMIT 6
`

type DashboardNeedsAttentionRow struct {
	Kind       string           `json:"kind"`
	RefID      int32            `json:"ref_id"`
	RefKind    string           `json:"ref_kind"`
	Subject    string           `json:"subject"`
	DetailHint string           `json:"detail_hint"`
	DueAt      pgtype.Timestamp `json:"due_at"`
}

// Waitlist entries that have been sitting uncontacted >7 days, and
// geckos that have been on HOLD >7 days without any status change.
// Top 6 merged by staleness (oldest first).
func (q *Queries) DashboardNeedsAttention(ctx context.Context) ([]DashboardNeedsAttentionRow, error) {
	rows, err := q.db.Query(ctx, dashboardNeedsAttention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardNeedsAttentionRow{}
	for rows.Next() {
		var i DashboardNeedsAttentionRow
		if err := rows.Scan(
			&i.Kind,
			&i.RefID,
			&i.RefKind,
			&i.Subject,
			&i.DetailHint,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentActivity = `-- name: DashboardRecentActivity :many
(
  SELECT 'gecko_created'::text AS kind,
         g.id                  AS ref_id,
         'gecko'::text         AS ref_kind,
         COALESCE(g.name, g.code) AS title,
         g.code                AS detail,
         g.created_at          AS at
  FROM geckos g
)
UNION ALL
(
  SELECT 'waitlist_created'::text AS kind,
         w.id                      AS ref_id,
         'waitlist'::text          AS ref_kind,
         'New waitlist signup'     AS title,
         w.email                   AS detail,
         w.created_at              AS at
  FROM waitlist_entries w
)
UNION ALL
(
  SELECT 'media_uploaded'::text AS kind,
         m.id                   AS ref_id,
         'gecko'::text          AS ref_kind,
         'Photo added to ' || COALESCE(g.name, g.code, '(unknown)') AS title,
         ''                     AS detail,
         m.uploaded_at          AS at
  FROM media m
  LEFT JOIN geckos g ON g.id = m.gecko_id
  WHERE m.gecko_id IS NOT NULL
)
ORDER BY at DESC
LIMIT 15
`

type DashboardRecentActivityRow struct {
	Kind    string           `json:"kind"`
	RefID   int32            `json:"ref_id"`
	RefKind string           `json:"ref_kind"`
	Title   string           `json:"title"`
	Detail  string           `json:"detail"`
	At      pgtype.Timestamp `json:"at"`
}

// Top 15 most-recent events across three sources. Keep the shape
// identical across branches so sqlc generates a single row type.
func (q *Queries) DashboardRecentActivity(ctx context.Context) ([]DashboardRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentActivityRow{}
	for rows.Next() {
		var i DashboardRecentActivityRow
		if err := rows.Scan(
			&i.Kind,
			&i.RefID,
			&i.RefKind,
			&i.Title,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardStats = `-- name: DashboardStats :one
SELECT
  (SELECT COUNT(*) FROM geckos)                              AS total_geckos,
  (SELECT COUNT(*) FROM geckos WHERE status = 'BREEDING')    AS breeding,
  (SELECT COUNT(*) FROM geckos WHERE status = 'AVAILABLE')   AS available,
  (SELECT COUNT(*) FROM waitlist_entries)                    AS waitlist
`

type DashboardStatsRow struct {
	TotalGeckos int64 `json:"total_geckos"`
	Breeding    int64 `json:"breeding"`
	Available   int64 `json:"available"`
	Waitlist    int64 `json:"waitlist"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.TotalGeckos,
		&i.Breeding,
		&i.Available,
		&i.Waitlist,
	)
	return i, err
}
