// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: geckos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGeckos = `-- name: CountGeckos :one
SELECT COUNT(*) FROM geckos
`

func (q *Queries) CountGeckos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGeckos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGeckosByStatus = `-- name: CountGeckosByStatus :many
SELECT status, COUNT(*) AS count
FROM geckos
GROUP BY status
`

type CountGeckosByStatusRow struct {
	Status GeckoStatus `json:"status"`
	Count  int64       `json:"count"`
}

func (q *Queries) CountGeckosByStatus(ctx context.Context) ([]CountGeckosByStatusRow, error) {
	rows, err := q.db.Query(ctx, countGeckosByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGeckosByStatusRow{}
	for rows.Next() {
		var i CountGeckosByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGecko = `-- name: CreateGecko :one
INSERT INTO geckos (
  code, name, species_id, sex, hatch_date, acquired_date,
  status, sire_id, dam_id, list_price_usd, notes
)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, 'AVAILABLE'::gecko_status), $8, $9, $10, $11)
RETURNING
  id, code, name, species_id, sex, hatch_date, acquired_date,
  status, sire_id, dam_id, list_price_usd, notes,
  created_at, updated_at
`

type CreateGeckoParams struct {
	Code         string         `json:"code"`
	Name         pgtype.Text    `json:"name"`
	SpeciesID    int32          `json:"species_id"`
	Sex          Sex            `json:"sex"`
	HatchDate    pgtype.Date    `json:"hatch_date"`
	AcquiredDate pgtype.Date    `json:"acquired_date"`
	Column7      interface{}    `json:"column_7"`
	SireID       pgtype.Int4    `json:"sire_id"`
	DamID        pgtype.Int4    `json:"dam_id"`
	ListPriceUsd pgtype.Numeric `json:"list_price_usd"`
	Notes        pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateGecko(ctx context.Context, arg CreateGeckoParams) (Gecko, error) {
	row := q.db.QueryRow(ctx, createGecko,
		arg.Code,
		arg.Name,
		arg.SpeciesID,
		arg.Sex,
		arg.HatchDate,
		arg.AcquiredDate,
		arg.Column7,
		arg.SireID,
		arg.DamID,
		arg.ListPriceUsd,
		arg.Notes,
	)
	var i Gecko
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpeciesID,
		&i.Sex,
		&i.HatchDate,
		&i.AcquiredDate,
		&i.Status,
		&i.SireID,
		&i.DamID,
		&i.ListPriceUsd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGeckoByCode = `-- name: GetGeckoByCode :one
SELECT
  g.id, g.code, g.name, g.species_id, g.sex, g.hatch_date, g.acquired_date,
  g.status, g.sire_id, g.dam_id, g.list_price_usd, g.notes,
  g.created_at, g.updated_at,
  sp.code AS species_code,
  sp.common_name AS species_common_name
FROM geckos g
JOIN species sp ON sp.id = g.species_id
WHERE g.code = $1
LIMIT 1
`

type GetGeckoByCodeRow struct {
	ID                int32            `json:"id"`
	Code              string           `json:"code"`
	Name              pgtype.Text      `json:"name"`
	SpeciesID         int32            `json:"species_id"`
	Sex               Sex              `json:"sex"`
	HatchDate         pgtype.Date      `json:"hatch_date"`
	AcquiredDate      pgtype.Date      `json:"acquired_date"`
	Status            GeckoStatus      `json:"status"`
	SireID            pgtype.Int4      `json:"sire_id"`
	DamID             pgtype.Int4      `json:"dam_id"`
	ListPriceUsd      pgtype.Numeric   `json:"list_price_usd"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	SpeciesCode       SpeciesCode      `json:"species_code"`
	SpeciesCommonName string           `json:"species_common_name"`
}

func (q *Queries) GetGeckoByCode(ctx context.Context, code string) (GetGeckoByCodeRow, error) {
	row := q.db.QueryRow(ctx, getGeckoByCode, code)
	var i GetGeckoByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpeciesID,
		&i.Sex,
		&i.HatchDate,
		&i.AcquiredDate,
		&i.Status,
		&i.SireID,
		&i.DamID,
		&i.ListPriceUsd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpeciesCode,
		&i.SpeciesCommonName,
	)
	return i, err
}

const getGeckoByID = `-- name: GetGeckoByID :one
SELECT
  g.id, g.code, g.name, g.species_id, g.sex, g.hatch_date, g.acquired_date,
  g.status, g.sire_id, g.dam_id, g.list_price_usd, g.notes,
  g.created_at, g.updated_at,
  sp.code AS species_code,
  sp.common_name AS species_common_name
FROM geckos g
JOIN species sp ON sp.id = g.species_id
WHERE g.id = $1
LIMIT 1
`

type GetGeckoByIDRow struct {
	ID                int32            `json:"id"`
	Code              string           `json:"code"`
	Name              pgtype.Text      `json:"name"`
	SpeciesID         int32            `json:"species_id"`
	Sex               Sex              `json:"sex"`
	HatchDate         pgtype.Date      `json:"hatch_date"`
	AcquiredDate      pgtype.Date      `json:"acquired_date"`
	Status            GeckoStatus      `json:"status"`
	SireID            pgtype.Int4      `json:"sire_id"`
	DamID             pgtype.Int4      `json:"dam_id"`
	ListPriceUsd      pgtype.Numeric   `json:"list_price_usd"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	SpeciesCode       SpeciesCode      `json:"species_code"`
	SpeciesCommonName string           `json:"species_common_name"`
}

func (q *Queries) GetGeckoByID(ctx context.Context, id int32) (GetGeckoByIDRow, error) {
	row := q.db.QueryRow(ctx, getGeckoByID, id)
	var i GetGeckoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpeciesID,
		&i.Sex,
		&i.HatchDate,
		&i.AcquiredDate,
		&i.Status,
		&i.SireID,
		&i.DamID,
		&i.ListPriceUsd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpeciesCode,
		&i.SpeciesCommonName,
	)
	return i, err
}

const listGeckos = `-- name: ListGeckos :many
SELECT
  g.id, g.code, g.name, g.species_id, g.sex, g.hatch_date, g.acquired_date,
  g.status, g.sire_id, g.dam_id, g.list_price_usd, g.notes,
  g.created_at, g.updated_at,
  sp.code AS species_code,
  sp.common_name AS species_common_name
FROM geckos g
JOIN species sp ON sp.id = g.species_id
ORDER BY g.code
`

type ListGeckosRow struct {
	ID                int32            `json:"id"`
	Code              string           `json:"code"`
	Name              pgtype.Text      `json:"name"`
	SpeciesID         int32            `json:"species_id"`
	Sex               Sex              `json:"sex"`
	HatchDate         pgtype.Date      `json:"hatch_date"`
	AcquiredDate      pgtype.Date      `json:"acquired_date"`
	Status            GeckoStatus      `json:"status"`
	SireID            pgtype.Int4      `json:"sire_id"`
	DamID             pgtype.Int4      `json:"dam_id"`
	ListPriceUsd      pgtype.Numeric   `json:"list_price_usd"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	SpeciesCode       SpeciesCode      `json:"species_code"`
	SpeciesCommonName string           `json:"species_common_name"`
}

func (q *Queries) ListGeckos(ctx context.Context) ([]ListGeckosRow, error) {
	rows, err := q.db.Query(ctx, listGeckos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeckosRow{}
	for rows.Next() {
		var i ListGeckosRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpeciesID,
			&i.Sex,
			&i.HatchDate,
			&i.AcquiredDate,
			&i.Status,
			&i.SireID,
			&i.DamID,
			&i.ListPriceUsd,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpeciesCode,
			&i.SpeciesCommonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
