// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gecko_genes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGeckoGene = `-- name: CreateGeckoGene :one
INSERT INTO gecko_genes (gecko_id, trait_id, zygosity)
VALUES ($1, $2, $3)
RETURNING id, gecko_id, trait_id, zygosity, created_at
`

type CreateGeckoGeneParams struct {
	GeckoID  int32    `json:"gecko_id"`
	TraitID  int32    `json:"trait_id"`
	Zygosity Zygosity `json:"zygosity"`
}

func (q *Queries) CreateGeckoGene(ctx context.Context, arg CreateGeckoGeneParams) (GeckoGene, error) {
	row := q.db.QueryRow(ctx, createGeckoGene, arg.GeckoID, arg.TraitID, arg.Zygosity)
	var i GeckoGene
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.TraitID,
		&i.Zygosity,
		&i.CreatedAt,
	)
	return i, err
}

const listGeckoGenes = `-- name: ListGeckoGenes :many
SELECT
  gg.id, gg.gecko_id, gg.trait_id, gg.zygosity, gg.created_at,
  gd.trait_name, gd.trait_code, gd.is_dominant, gd.species_id
FROM gecko_genes gg
JOIN genetic_dictionary gd ON gd.id = gg.trait_id
ORDER BY gg.gecko_id, gd.trait_name
`

type ListGeckoGenesRow struct {
	ID         int32            `json:"id"`
	GeckoID    int32            `json:"gecko_id"`
	TraitID    int32            `json:"trait_id"`
	Zygosity   Zygosity         `json:"zygosity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	TraitName  string           `json:"trait_name"`
	TraitCode  pgtype.Text      `json:"trait_code"`
	IsDominant bool             `json:"is_dominant"`
	SpeciesID  int32            `json:"species_id"`
}

func (q *Queries) ListGeckoGenes(ctx context.Context) ([]ListGeckoGenesRow, error) {
	rows, err := q.db.Query(ctx, listGeckoGenes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeckoGenesRow{}
	for rows.Next() {
		var i ListGeckoGenesRow
		if err := rows.Scan(
			&i.ID,
			&i.GeckoID,
			&i.TraitID,
			&i.Zygosity,
			&i.CreatedAt,
			&i.TraitName,
			&i.TraitCode,
			&i.IsDominant,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenesForGecko = `-- name: ListGenesForGecko :many
SELECT
  gg.id, gg.gecko_id, gg.trait_id, gg.zygosity, gg.created_at,
  gd.trait_name, gd.trait_code, gd.is_dominant, gd.species_id
FROM gecko_genes gg
JOIN genetic_dictionary gd ON gd.id = gg.trait_id
WHERE gg.gecko_id = $1
ORDER BY gd.trait_name
`

type ListGenesForGeckoRow struct {
	ID         int32            `json:"id"`
	GeckoID    int32            `json:"gecko_id"`
	TraitID    int32            `json:"trait_id"`
	Zygosity   Zygosity         `json:"zygosity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	TraitName  string           `json:"trait_name"`
	TraitCode  pgtype.Text      `json:"trait_code"`
	IsDominant bool             `json:"is_dominant"`
	SpeciesID  int32            `json:"species_id"`
}

func (q *Queries) ListGenesForGecko(ctx context.Context, geckoID int32) ([]ListGenesForGeckoRow, error) {
	rows, err := q.db.Query(ctx, listGenesForGecko, geckoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenesForGeckoRow{}
	for rows.Next() {
		var i ListGenesForGeckoRow
		if err := rows.Scan(
			&i.ID,
			&i.GeckoID,
			&i.TraitID,
			&i.Zygosity,
			&i.CreatedAt,
			&i.TraitName,
			&i.TraitCode,
			&i.IsDominant,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
