// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: genetic_dictionary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrait = `-- name: CreateTrait :one
INSERT INTO genetic_dictionary (species_id, trait_name, trait_code, description, is_dominant)
VALUES ($1, $2, $3, $4, COALESCE($5, FALSE))
RETURNING id, species_id, trait_name, trait_code, description, is_dominant, created_at, updated_at
`

type CreateTraitParams struct {
	SpeciesID   int32       `json:"species_id"`
	TraitName   string      `json:"trait_name"`
	TraitCode   pgtype.Text `json:"trait_code"`
	Description pgtype.Text `json:"description"`
	Column5     interface{} `json:"column_5"`
}

func (q *Queries) CreateTrait(ctx context.Context, arg CreateTraitParams) (GeneticDictionary, error) {
	row := q.db.QueryRow(ctx, createTrait,
		arg.SpeciesID,
		arg.TraitName,
		arg.TraitCode,
		arg.Description,
		arg.Column5,
	)
	var i GeneticDictionary
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.TraitName,
		&i.TraitCode,
		&i.Description,
		&i.IsDominant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTraitByNameAndSpecies = `-- name: GetTraitByNameAndSpecies :one
SELECT id, species_id, trait_name, trait_code, description, is_dominant, created_at, updated_at
FROM genetic_dictionary
WHERE species_id = $1 AND LOWER(trait_name) = LOWER($2)
LIMIT 1
`

type GetTraitByNameAndSpeciesParams struct {
	SpeciesID int32  `json:"species_id"`
	Lower     string `json:"lower"`
}

func (q *Queries) GetTraitByNameAndSpecies(ctx context.Context, arg GetTraitByNameAndSpeciesParams) (GeneticDictionary, error) {
	row := q.db.QueryRow(ctx, getTraitByNameAndSpecies, arg.SpeciesID, arg.Lower)
	var i GeneticDictionary
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.TraitName,
		&i.TraitCode,
		&i.Description,
		&i.IsDominant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTraits = `-- name: ListTraits :many
SELECT id, species_id, trait_name, trait_code, description, is_dominant, created_at, updated_at
FROM genetic_dictionary
ORDER BY species_id, trait_name
`

func (q *Queries) ListTraits(ctx context.Context) ([]GeneticDictionary, error) {
	rows, err := q.db.Query(ctx, listTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneticDictionary{}
	for rows.Next() {
		var i GeneticDictionary
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.TraitName,
			&i.TraitCode,
			&i.Description,
			&i.IsDominant,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraitsBySpecies = `-- name: ListTraitsBySpecies :many
SELECT id, species_id, trait_name, trait_code, description, is_dominant, created_at, updated_at
FROM genetic_dictionary
WHERE species_id = $1
ORDER BY trait_name
`

func (q *Queries) ListTraitsBySpecies(ctx context.Context, speciesID int32) ([]GeneticDictionary, error) {
	rows, err := q.db.Query(ctx, listTraitsBySpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneticDictionary{}
	for rows.Next() {
		var i GeneticDictionary
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.TraitName,
			&i.TraitCode,
			&i.Description,
			&i.IsDominant,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
