// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: listings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachGeckoToListing = `-- name: AttachGeckoToListing :exec
INSERT INTO listing_geckos (listing_id, gecko_id)
VALUES ($1, $2)
`

type AttachGeckoToListingParams struct {
	ListingID int32 `json:"listing_id"`
	GeckoID   int32 `json:"gecko_id"`
}

func (q *Queries) AttachGeckoToListing(ctx context.Context, arg AttachGeckoToListingParams) error {
	_, err := q.db.Exec(ctx, attachGeckoToListing, arg.ListingID, arg.GeckoID)
	return err
}

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
  sku, type, title, description, price_usd, deposit_usd, status,
  cover_photo_url, listed_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, COALESCE($7, 'DRAFT'::listing_status),
  $8,
  CASE WHEN COALESCE($7, 'DRAFT'::listing_status) = 'LISTED'::listing_status THEN NOW() ELSE NULL END
)
RETURNING
  id, sku, type, title, description, price_usd, deposit_usd, status,
  cover_photo_url, listed_at, sold_at, archived_at, created_at, updated_at
`

type CreateListingParams struct {
	Sku           pgtype.Text    `json:"sku"`
	Type          ListingType    `json:"type"`
	Title         string         `json:"title"`
	Description   pgtype.Text    `json:"description"`
	PriceUsd      pgtype.Numeric `json:"price_usd"`
	DepositUsd    pgtype.Numeric `json:"deposit_usd"`
	Column7       interface{}    `json:"column_7"`
	CoverPhotoUrl pgtype.Text    `json:"cover_photo_url"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.Sku,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.PriceUsd,
		arg.DepositUsd,
		arg.Column7,
		arg.CoverPhotoUrl,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.PriceUsd,
		&i.DepositUsd,
		&i.Status,
		&i.CoverPhotoUrl,
		&i.ListedAt,
		&i.SoldAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComponentsForListing = `-- name: DeleteComponentsForListing :exec
DELETE FROM listing_components WHERE listing_id = $1
`

func (q *Queries) DeleteComponentsForListing(ctx context.Context, listingID int32) error {
	_, err := q.db.Exec(ctx, deleteComponentsForListing, listingID)
	return err
}

const deleteListing = `-- name: DeleteListing :exec
DELETE FROM listings WHERE id = $1
`

func (q *Queries) DeleteListing(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteListing, id)
	return err
}

const detachGeckosForListing = `-- name: DetachGeckosForListing :exec
DELETE FROM listing_geckos WHERE listing_id = $1
`

func (q *Queries) DetachGeckosForListing(ctx context.Context, listingID int32) error {
	_, err := q.db.Exec(ctx, detachGeckosForListing, listingID)
	return err
}

const getListing = `-- name: GetListing :one
SELECT
  l.id, l.sku, l.type, l.title, l.description, l.price_usd, l.deposit_usd,
  l.status, l.cover_photo_url, l.listed_at, l.sold_at, l.archived_at,
  l.created_at, l.updated_at
FROM listings l
WHERE l.id = $1
LIMIT 1
`

func (q *Queries) GetListing(ctx context.Context, id int32) (Listing, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.PriceUsd,
		&i.DepositUsd,
		&i.Status,
		&i.CoverPhotoUrl,
		&i.ListedAt,
		&i.SoldAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListingBySku = `-- name: GetListingBySku :one
SELECT id FROM listings WHERE sku = $1 LIMIT 1
`

func (q *Queries) GetListingBySku(ctx context.Context, sku pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getListingBySku, sku)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listComponentsForListing = `-- name: ListComponentsForListing :many
SELECT
  lc.component_listing_id,
  lc.quantity,
  l.title,
  l.type,
  l.price_usd
FROM listing_components lc
JOIN listings l ON l.id = lc.component_listing_id
WHERE lc.listing_id = $1
ORDER BY l.title
`

type ListComponentsForListingRow struct {
	ComponentListingID int32          `json:"component_listing_id"`
	Quantity           int32          `json:"quantity"`
	Title              string         `json:"title"`
	Type               ListingType    `json:"type"`
	PriceUsd           pgtype.Numeric `json:"price_usd"`
}

func (q *Queries) ListComponentsForListing(ctx context.Context, listingID int32) ([]ListComponentsForListingRow, error) {
	rows, err := q.db.Query(ctx, listComponentsForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentsForListingRow{}
	for rows.Next() {
		var i ListComponentsForListingRow
		if err := rows.Scan(
			&i.ComponentListingID,
			&i.Quantity,
			&i.Title,
			&i.Type,
			&i.PriceUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeckosForListing = `-- name: ListGeckosForListing :many
SELECT
  lg.gecko_id,
  g.code,
  g.name,
  sp.code AS species_code
FROM listing_geckos lg
JOIN geckos g   ON g.id = lg.gecko_id
JOIN species sp ON sp.id = g.species_id
WHERE lg.listing_id = $1
ORDER BY g.code
`

type ListGeckosForListingRow struct {
	GeckoID     int32       `json:"gecko_id"`
	Code        string      `json:"code"`
	Name        pgtype.Text `json:"name"`
	SpeciesCode SpeciesCode `json:"species_code"`
}

func (q *Queries) ListGeckosForListing(ctx context.Context, listingID int32) ([]ListGeckosForListingRow, error) {
	rows, err := q.db.Query(ctx, listGeckosForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeckosForListingRow{}
	for rows.Next() {
		var i ListGeckosForListingRow
		if err := rows.Scan(
			&i.GeckoID,
			&i.Code,
			&i.Name,
			&i.SpeciesCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListings = `-- name: ListListings :many
SELECT
  l.id, l.sku, l.type, l.title, l.description, l.price_usd, l.deposit_usd,
  l.status, l.cover_photo_url, l.listed_at, l.sold_at, l.archived_at,
  l.created_at, l.updated_at,
  COALESCE(gc.n, 0)::int AS gecko_count,
  COALESCE(cc.n, 0)::int AS component_count
FROM listings l
LEFT JOIN (
  SELECT listing_id, COUNT(*) AS n
  FROM listing_geckos GROUP BY listing_id
) gc ON gc.listing_id = l.id
LEFT JOIN (
  SELECT listing_id, COUNT(*) AS n
  FROM listing_components GROUP BY listing_id
) cc ON cc.listing_id = l.id
ORDER BY
  CASE l.status
    WHEN 'LISTED'   THEN 0
    WHEN 'RESERVED' THEN 1
    WHEN 'DRAFT'    THEN 2
    WHEN 'SOLD'     THEN 3
    WHEN 'ARCHIVED' THEN 4
  END,
  l.created_at DESC
`

type ListListingsRow struct {
	ID             int32            `json:"id"`
	Sku            pgtype.Text      `json:"sku"`
	Type           ListingType      `json:"type"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	PriceUsd       pgtype.Numeric   `json:"price_usd"`
	DepositUsd     pgtype.Numeric   `json:"deposit_usd"`
	Status         ListingStatus    `json:"status"`
	CoverPhotoUrl  pgtype.Text      `json:"cover_photo_url"`
	ListedAt       pgtype.Timestamp `json:"listed_at"`
	SoldAt         pgtype.Timestamp `json:"sold_at"`
	ArchivedAt     pgtype.Timestamp `json:"archived_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	GeckoCount     int32            `json:"gecko_count"`
	ComponentCount int32            `json:"component_count"`
}

func (q *Queries) ListListings(ctx context.Context) ([]ListListingsRow, error) {
	rows, err := q.db.Query(ctx, listListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsRow{}
	for rows.Next() {
		var i ListListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.PriceUsd,
			&i.DepositUsd,
			&i.Status,
			&i.CoverPhotoUrl,
			&i.ListedAt,
			&i.SoldAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeckoCount,
			&i.ComponentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsForGecko = `-- name: ListListingsForGecko :many
SELECT
  l.id, l.title, l.type, l.status, l.price_usd
FROM listings l
JOIN listing_geckos lg ON lg.listing_id = l.id
WHERE lg.gecko_id = $1
ORDER BY l.created_at DESC
`

type ListListingsForGeckoRow struct {
	ID       int32          `json:"id"`
	Title    string         `json:"title"`
	Type     ListingType    `json:"type"`
	Status   ListingStatus  `json:"status"`
	PriceUsd pgtype.Numeric `json:"price_usd"`
}

// Used by admin gecko detail page.
func (q *Queries) ListListingsForGecko(ctx context.Context, geckoID int32) ([]ListListingsForGeckoRow, error) {
	rows, err := q.db.Query(ctx, listListingsForGecko, geckoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsForGeckoRow{}
	for rows.Next() {
		var i ListListingsForGeckoRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.PriceUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingComponent = `-- name: SetListingComponent :exec
INSERT INTO listing_components (listing_id, component_listing_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (listing_id, component_listing_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type SetListingComponentParams struct {
	ListingID          int32 `json:"listing_id"`
	ComponentListingID int32 `json:"component_listing_id"`
	Quantity           int32 `json:"quantity"`
}

func (q *Queries) SetListingComponent(ctx context.Context, arg SetListingComponentParams) error {
	_, err := q.db.Exec(ctx, setListingComponent, arg.ListingID, arg.ComponentListingID, arg.Quantity)
	return err
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings SET
  sku             = $2,
  title           = $3,
  description     = $4,
  price_usd       = $5,
  deposit_usd     = $6,
  status          = $7,
  cover_photo_url = $8,
  listed_at       = CASE
                      WHEN $7 = 'LISTED'::listing_status AND listed_at IS NULL THEN NOW()
                      ELSE listed_at
                    END,
  sold_at         = CASE
                      WHEN $7 = 'SOLD'::listing_status AND sold_at IS NULL THEN NOW()
                      ELSE sold_at
                    END,
  archived_at     = CASE
                      WHEN $7 = 'ARCHIVED'::listing_status AND archived_at IS NULL THEN NOW()
                      ELSE archived_at
                    END,
  updated_at      = NOW()
WHERE id = $1
RETURNING
  id, sku, type, title, description, price_usd, deposit_usd, status,
  cover_photo_url, listed_at, sold_at, archived_at, created_at, updated_at
`

type UpdateListingParams struct {
	ID            int32          `json:"id"`
	Sku           pgtype.Text    `json:"sku"`
	Title         string         `json:"title"`
	Description   pgtype.Text    `json:"description"`
	PriceUsd      pgtype.Numeric `json:"price_usd"`
	DepositUsd    pgtype.Numeric `json:"deposit_usd"`
	Status        ListingStatus  `json:"status"`
	CoverPhotoUrl pgtype.Text    `json:"cover_photo_url"`
}

// Status transitions into LISTED/SOLD/ARCHIVED auto-stamp the matching
// timestamp the first time it happens; existing stamps are preserved so
// the audit trail survives later status moves.
func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.ID,
		arg.Sku,
		arg.Title,
		arg.Description,
		arg.PriceUsd,
		arg.DepositUsd,
		arg.Status,
		arg.CoverPhotoUrl,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.PriceUsd,
		&i.DepositUsd,
		&i.Status,
		&i.CoverPhotoUrl,
		&i.ListedAt,
		&i.SoldAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
