// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaForGecko = `-- name: CountMediaForGecko :one
SELECT COUNT(*) FROM media WHERE gecko_id = $1
`

func (q *Queries) CountMediaForGecko(ctx context.Context, geckoID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaForGecko, geckoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (gecko_id, url, type, caption, display_order)
VALUES ($1, $2, COALESCE($3, 'GALLERY'::media_type), $4, COALESCE($5, 0))
RETURNING id, gecko_id, url, type, caption, display_order, uploaded_at
`

type CreateMediaParams struct {
	GeckoID pgtype.Int4 `json:"gecko_id"`
	Url     string      `json:"url"`
	Column3 interface{} `json:"column_3"`
	Caption pgtype.Text `json:"caption"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.GeckoID,
		arg.Url,
		arg.Column3,
		arg.Caption,
		arg.Column5,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getCoverForGecko = `-- name: GetCoverForGecko :one
SELECT id, gecko_id, url, type, caption, display_order, uploaded_at
FROM media
WHERE gecko_id = $1
ORDER BY display_order, uploaded_at
LIMIT 1
`

func (q *Queries) GetCoverForGecko(ctx context.Context, geckoID pgtype.Int4) (Medium, error) {
	row := q.db.QueryRow(ctx, getCoverForGecko, geckoID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, gecko_id, url, type, caption, display_order, uploaded_at
FROM media
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMediaByID(ctx context.Context, id int32) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const listCoverMediaForGeckos = `-- name: ListCoverMediaForGeckos :many
SELECT DISTINCT ON (gecko_id) gecko_id, id, url, type, caption, display_order, uploaded_at
FROM media
WHERE gecko_id IS NOT NULL
ORDER BY gecko_id, display_order, uploaded_at
`

type ListCoverMediaForGeckosRow struct {
	GeckoID      pgtype.Int4      `json:"gecko_id"`
	ID           int32            `json:"id"`
	Url          string           `json:"url"`
	Type         MediaType        `json:"type"`
	Caption      pgtype.Text      `json:"caption"`
	DisplayOrder int32            `json:"display_order"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
}

// First photo per gecko (lowest display_order, then oldest) so the list
// view can render covers in a single round trip instead of N queries.
func (q *Queries) ListCoverMediaForGeckos(ctx context.Context) ([]ListCoverMediaForGeckosRow, error) {
	rows, err := q.db.Query(ctx, listCoverMediaForGeckos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoverMediaForGeckosRow{}
	for rows.Next() {
		var i ListCoverMediaForGeckosRow
		if err := rows.Scan(
			&i.GeckoID,
			&i.ID,
			&i.Url,
			&i.Type,
			&i.Caption,
			&i.DisplayOrder,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaForGecko = `-- name: ListMediaForGecko :many
SELECT id, gecko_id, url, type, caption, display_order, uploaded_at
FROM media
WHERE gecko_id = $1
ORDER BY display_order, uploaded_at
`

func (q *Queries) ListMediaForGecko(ctx context.Context, geckoID pgtype.Int4) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaForGecko, geckoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.GeckoID,
			&i.Url,
			&i.Type,
			&i.Caption,
			&i.DisplayOrder,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaIDsForGeckoOrdered = `-- name: ListMediaIDsForGeckoOrdered :many
SELECT id
FROM media
WHERE gecko_id = $1
ORDER BY display_order, uploaded_at
`

// Returns the media ids for a gecko in the same (display_order, uploaded_at)
// order the client sees. Used by set-cover to reassign display_order.
func (q *Queries) ListMediaIDsForGeckoOrdered(ctx context.Context, geckoID pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, listMediaIDsForGeckoOrdered, geckoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaCaption = `-- name: UpdateMediaCaption :one
UPDATE media
SET caption = $2
WHERE id = $1
RETURNING id, gecko_id, url, type, caption, display_order, uploaded_at
`

type UpdateMediaCaptionParams struct {
	ID      int32       `json:"id"`
	Caption pgtype.Text `json:"caption"`
}

func (q *Queries) UpdateMediaCaption(ctx context.Context, arg UpdateMediaCaptionParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaCaption, arg.ID, arg.Caption)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const updateMediaCaptionAndOrder = `-- name: UpdateMediaCaptionAndOrder :one
UPDATE media
SET caption = $2, display_order = $3
WHERE id = $1
RETURNING id, gecko_id, url, type, caption, display_order, uploaded_at
`

type UpdateMediaCaptionAndOrderParams struct {
	ID           int32       `json:"id"`
	Caption      pgtype.Text `json:"caption"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) UpdateMediaCaptionAndOrder(ctx context.Context, arg UpdateMediaCaptionAndOrderParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaCaptionAndOrder, arg.ID, arg.Caption, arg.DisplayOrder)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const updateMediaDisplayOrder = `-- name: UpdateMediaDisplayOrder :one
UPDATE media
SET display_order = $2
WHERE id = $1
RETURNING id, gecko_id, url, type, caption, display_order, uploaded_at
`

type UpdateMediaDisplayOrderParams struct {
	ID           int32 `json:"id"`
	DisplayOrder int32 `json:"display_order"`
}

func (q *Queries) UpdateMediaDisplayOrder(ctx context.Context, arg UpdateMediaDisplayOrderParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaDisplayOrder, arg.ID, arg.DisplayOrder)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}
