// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (gecko_id, url, type, caption, display_order)
VALUES ($1, $2, COALESCE($3, 'GALLERY'::media_type), $4, COALESCE($5, 0))
RETURNING id, gecko_id, url, type, caption, display_order, uploaded_at
`

type CreateMediaParams struct {
	GeckoID pgtype.Int4 `json:"gecko_id"`
	Url     string      `json:"url"`
	Column3 interface{} `json:"column_3"`
	Caption pgtype.Text `json:"caption"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.GeckoID,
		arg.Url,
		arg.Column3,
		arg.Caption,
		arg.Column5,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const getCoverForGecko = `-- name: GetCoverForGecko :one
SELECT id, gecko_id, url, type, caption, display_order, uploaded_at
FROM media
WHERE gecko_id = $1
ORDER BY display_order, uploaded_at
LIMIT 1
`

func (q *Queries) GetCoverForGecko(ctx context.Context, geckoID pgtype.Int4) (Medium, error) {
	row := q.db.QueryRow(ctx, getCoverForGecko, geckoID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GeckoID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.DisplayOrder,
		&i.UploadedAt,
	)
	return i, err
}

const listMediaForGecko = `-- name: ListMediaForGecko :many
SELECT id, gecko_id, url, type, caption, display_order, uploaded_at
FROM media
WHERE gecko_id = $1
ORDER BY display_order, uploaded_at
`

func (q *Queries) ListMediaForGecko(ctx context.Context, geckoID pgtype.Int4) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaForGecko, geckoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.GeckoID,
			&i.Url,
			&i.Type,
			&i.Caption,
			&i.DisplayOrder,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
