// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Name         pgtype.Text      `json:"name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type WaitlistEntry struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	Telegram     pgtype.Text      `json:"telegram"`
	Phone        pgtype.Text      `json:"phone"`
	InterestedIn pgtype.Text      `json:"interested_in"`
	Source       pgtype.Text      `json:"source"`
	Notes        pgtype.Text      `json:"notes"`
	ContactedAt  pgtype.Timestamp `json:"contacted_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
