// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: morph_combos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMorphCombo = `-- name: CreateMorphCombo :one
INSERT INTO morph_combos
  (species_id, name, code, description, notes, example_photo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, species_id, name, code, description, notes, example_photo_url,
          created_at, updated_at
`

type CreateMorphComboParams struct {
	SpeciesID       int32       `json:"species_id"`
	Name            string      `json:"name"`
	Code            pgtype.Text `json:"code"`
	Description     pgtype.Text `json:"description"`
	Notes           pgtype.Text `json:"notes"`
	ExamplePhotoUrl pgtype.Text `json:"example_photo_url"`
}

func (q *Queries) CreateMorphCombo(ctx context.Context, arg CreateMorphComboParams) (MorphCombo, error) {
	row := q.db.QueryRow(ctx, createMorphCombo,
		arg.SpeciesID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Notes,
		arg.ExamplePhotoUrl,
	)
	var i MorphCombo
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Notes,
		&i.ExamplePhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMorphCombo = `-- name: DeleteMorphCombo :exec
DELETE FROM morph_combos WHERE id = $1
`

func (q *Queries) DeleteMorphCombo(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMorphCombo, id)
	return err
}

const deleteMorphComboTraits = `-- name: DeleteMorphComboTraits :exec
DELETE FROM morph_combo_traits WHERE combo_id = $1
`

func (q *Queries) DeleteMorphComboTraits(ctx context.Context, comboID int32) error {
	_, err := q.db.Exec(ctx, deleteMorphComboTraits, comboID)
	return err
}

const getMorphCombo = `-- name: GetMorphCombo :one
SELECT id, species_id, name, code, description, notes, example_photo_url,
       created_at, updated_at
FROM morph_combos
WHERE id = $1
`

func (q *Queries) GetMorphCombo(ctx context.Context, id int32) (MorphCombo, error) {
	row := q.db.QueryRow(ctx, getMorphCombo, id)
	var i MorphCombo
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Notes,
		&i.ExamplePhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMorphComboTrait = `-- name: InsertMorphComboTrait :exec
INSERT INTO morph_combo_traits (combo_id, trait_id, required_zygosity)
VALUES ($1, $2, $3)
`

type InsertMorphComboTraitParams struct {
	ComboID          int32    `json:"combo_id"`
	TraitID          int32    `json:"trait_id"`
	RequiredZygosity Zygosity `json:"required_zygosity"`
}

func (q *Queries) InsertMorphComboTrait(ctx context.Context, arg InsertMorphComboTraitParams) error {
	_, err := q.db.Exec(ctx, insertMorphComboTrait, arg.ComboID, arg.TraitID, arg.RequiredZygosity)
	return err
}

const listAllMorphCombosWithTraits = `-- name: ListAllMorphCombosWithTraits :many
SELECT
  mc.id        AS combo_id,
  mc.name      AS combo_name,
  mc.species_id,
  mct.trait_id,
  mct.required_zygosity
FROM morph_combos mc
JOIN morph_combo_traits mct ON mct.combo_id = mc.id
ORDER BY mc.species_id, mc.id, mct.trait_id
`

type ListAllMorphCombosWithTraitsRow struct {
	ComboID          int32    `json:"combo_id"`
	ComboName        string   `json:"combo_name"`
	SpeciesID        int32    `json:"species_id"`
	TraitID          int32    `json:"trait_id"`
	RequiredZygosity Zygosity `json:"required_zygosity"`
}

// Bulk load for DetectMorph — one round trip fetches the full combo catalog.
func (q *Queries) ListAllMorphCombosWithTraits(ctx context.Context) ([]ListAllMorphCombosWithTraitsRow, error) {
	rows, err := q.db.Query(ctx, listAllMorphCombosWithTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMorphCombosWithTraitsRow{}
	for rows.Next() {
		var i ListAllMorphCombosWithTraitsRow
		if err := rows.Scan(
			&i.ComboID,
			&i.ComboName,
			&i.SpeciesID,
			&i.TraitID,
			&i.RequiredZygosity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMorphComboTraits = `-- name: ListMorphComboTraits :many
SELECT mct.combo_id, mct.trait_id, mct.required_zygosity,
       gd.trait_name, gd.trait_code
FROM morph_combo_traits mct
JOIN genetic_dictionary gd ON gd.id = mct.trait_id
WHERE mct.combo_id = ANY($1::int[])
ORDER BY mct.combo_id, gd.trait_name
`

type ListMorphComboTraitsRow struct {
	ComboID          int32       `json:"combo_id"`
	TraitID          int32       `json:"trait_id"`
	RequiredZygosity Zygosity    `json:"required_zygosity"`
	TraitName        string      `json:"trait_name"`
	TraitCode        pgtype.Text `json:"trait_code"`
}

func (q *Queries) ListMorphComboTraits(ctx context.Context, dollar_1 []int32) ([]ListMorphComboTraitsRow, error) {
	rows, err := q.db.Query(ctx, listMorphComboTraits, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMorphComboTraitsRow{}
	for rows.Next() {
		var i ListMorphComboTraitsRow
		if err := rows.Scan(
			&i.ComboID,
			&i.TraitID,
			&i.RequiredZygosity,
			&i.TraitName,
			&i.TraitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMorphCombos = `-- name: ListMorphCombos :many
SELECT id, species_id, name, code, description, notes, example_photo_url,
       created_at, updated_at
FROM morph_combos
ORDER BY species_id, name
`

func (q *Queries) ListMorphCombos(ctx context.Context) ([]MorphCombo, error) {
	rows, err := q.db.Query(ctx, listMorphCombos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MorphCombo{}
	for rows.Next() {
		var i MorphCombo
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Notes,
			&i.ExamplePhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMorphCombosBySpecies = `-- name: ListMorphCombosBySpecies :many
SELECT id, species_id, name, code, description, notes, example_photo_url,
       created_at, updated_at
FROM morph_combos
WHERE species_id = $1
ORDER BY name
`

func (q *Queries) ListMorphCombosBySpecies(ctx context.Context, speciesID int32) ([]MorphCombo, error) {
	rows, err := q.db.Query(ctx, listMorphCombosBySpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MorphCombo{}
	for rows.Next() {
		var i MorphCombo
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Notes,
			&i.ExamplePhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMorphCombo = `-- name: UpdateMorphCombo :one
UPDATE morph_combos
SET name = $2, code = $3, description = $4, notes = $5,
    example_photo_url = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, species_id, name, code, description, notes, example_photo_url,
          created_at, updated_at
`

type UpdateMorphComboParams struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Code            pgtype.Text `json:"code"`
	Description     pgtype.Text `json:"description"`
	Notes           pgtype.Text `json:"notes"`
	ExamplePhotoUrl pgtype.Text `json:"example_photo_url"`
}

func (q *Queries) UpdateMorphCombo(ctx context.Context, arg UpdateMorphComboParams) (MorphCombo, error) {
	row := q.db.QueryRow(ctx, updateMorphCombo,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Notes,
		arg.ExamplePhotoUrl,
	)
	var i MorphCombo
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Notes,
		&i.ExamplePhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
