// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailableGeckoByCode = `-- name: GetAvailableGeckoByCode :one
SELECT
    g.id,
    g.code,
    g.name,
    g.species_id,
    g.sex,
    g.hatch_date,
    g.acquired_date,
    g.status,
    g.sire_id,
    g.dam_id,
    g.notes,
    g.created_at,
    g.updated_at,
    s.code         AS species_code,
    s.common_name  AS species_common_name,
    l.price_usd    AS list_price_usd
FROM geckos g
JOIN species s       ON s.id = g.species_id
JOIN listing_geckos lg ON lg.gecko_id = g.id
JOIN listings l        ON l.id = lg.listing_id
                      AND l.type = 'GECKO'
                      AND l.status = 'LISTED'
WHERE g.code = $1
LIMIT 1
`

type GetAvailableGeckoByCodeRow struct {
	ID                int32            `json:"id"`
	Code              string           `json:"code"`
	Name              pgtype.Text      `json:"name"`
	SpeciesID         int32            `json:"species_id"`
	Sex               Sex              `json:"sex"`
	HatchDate         pgtype.Date      `json:"hatch_date"`
	AcquiredDate      pgtype.Date      `json:"acquired_date"`
	Status            GeckoStatus      `json:"status"`
	SireID            pgtype.Int4      `json:"sire_id"`
	DamID             pgtype.Int4      `json:"dam_id"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	SpeciesCode       SpeciesCode      `json:"species_code"`
	SpeciesCommonName string           `json:"species_common_name"`
	ListPriceUsd      pgtype.Numeric   `json:"list_price_usd"`
}

func (q *Queries) GetAvailableGeckoByCode(ctx context.Context, code string) (GetAvailableGeckoByCodeRow, error) {
	row := q.db.QueryRow(ctx, getAvailableGeckoByCode, code)
	var i GetAvailableGeckoByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpeciesID,
		&i.Sex,
		&i.HatchDate,
		&i.AcquiredDate,
		&i.Status,
		&i.SireID,
		&i.DamID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpeciesCode,
		&i.SpeciesCommonName,
		&i.ListPriceUsd,
	)
	return i, err
}

const listAvailableGeckos = `-- name: ListAvailableGeckos :many
SELECT
    g.id,
    g.code,
    g.name,
    g.species_id,
    g.sex,
    g.hatch_date,
    g.acquired_date,
    g.status,
    g.sire_id,
    g.dam_id,
    g.notes,
    g.created_at,
    g.updated_at,
    s.code         AS species_code,
    s.common_name  AS species_common_name,
    l.price_usd    AS list_price_usd
FROM geckos g
JOIN species s       ON s.id = g.species_id
JOIN listing_geckos lg ON lg.gecko_id = g.id
JOIN listings l        ON l.id = lg.listing_id
                      AND l.type = 'GECKO'
                      AND l.status = 'LISTED'
ORDER BY g.created_at DESC
`

type ListAvailableGeckosRow struct {
	ID                int32            `json:"id"`
	Code              string           `json:"code"`
	Name              pgtype.Text      `json:"name"`
	SpeciesID         int32            `json:"species_id"`
	Sex               Sex              `json:"sex"`
	HatchDate         pgtype.Date      `json:"hatch_date"`
	AcquiredDate      pgtype.Date      `json:"acquired_date"`
	Status            GeckoStatus      `json:"status"`
	SireID            pgtype.Int4      `json:"sire_id"`
	DamID             pgtype.Int4      `json:"dam_id"`
	Notes             pgtype.Text      `json:"notes"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	SpeciesCode       SpeciesCode      `json:"species_code"`
	SpeciesCommonName string           `json:"species_common_name"`
	ListPriceUsd      pgtype.Numeric   `json:"list_price_usd"`
}

func (q *Queries) ListAvailableGeckos(ctx context.Context) ([]ListAvailableGeckosRow, error) {
	rows, err := q.db.Query(ctx, listAvailableGeckos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableGeckosRow{}
	for rows.Next() {
		var i ListAvailableGeckosRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpeciesID,
			&i.Sex,
			&i.HatchDate,
			&i.AcquiredDate,
			&i.Status,
			&i.SireID,
			&i.DamID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpeciesCode,
			&i.SpeciesCommonName,
			&i.ListPriceUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGenesByGeckoIDs = `-- name: ListPublicGenesByGeckoIDs :many
SELECT
  gg.gecko_id,
  gd.trait_name,
  gd.trait_code,
  gg.zygosity
FROM gecko_genes gg
JOIN genetic_dictionary gd ON gd.id = gg.trait_id
WHERE gg.gecko_id = ANY($1::int[])
ORDER BY gg.gecko_id, gd.trait_name
`

type ListPublicGenesByGeckoIDsRow struct {
	GeckoID   int32       `json:"gecko_id"`
	TraitName string      `json:"trait_name"`
	TraitCode pgtype.Text `json:"trait_code"`
	Zygosity  Zygosity    `json:"zygosity"`
}

// Used to compose morphs for the list endpoint in one round trip.
func (q *Queries) ListPublicGenesByGeckoIDs(ctx context.Context, dollar_1 []int32) ([]ListPublicGenesByGeckoIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublicGenesByGeckoIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicGenesByGeckoIDsRow{}
	for rows.Next() {
		var i ListPublicGenesByGeckoIDsRow
		if err := rows.Scan(
			&i.GeckoID,
			&i.TraitName,
			&i.TraitCode,
			&i.Zygosity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMediaByGeckoIDs = `-- name: ListPublicMediaByGeckoIDs :many
SELECT DISTINCT ON (gecko_id) gecko_id, url, caption, display_order, uploaded_at
FROM media
WHERE gecko_id = ANY($1::int[])
ORDER BY gecko_id, display_order, uploaded_at
`

type ListPublicMediaByGeckoIDsRow struct {
	GeckoID      pgtype.Int4      `json:"gecko_id"`
	Url          string           `json:"url"`
	Caption      pgtype.Text      `json:"caption"`
	DisplayOrder int32            `json:"display_order"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
}

// Used to pre-load cover photos (first by display_order) for the list view.
func (q *Queries) ListPublicMediaByGeckoIDs(ctx context.Context, dollar_1 []int32) ([]ListPublicMediaByGeckoIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublicMediaByGeckoIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicMediaByGeckoIDsRow{}
	for rows.Next() {
		var i ListPublicMediaByGeckoIDsRow
		if err := rows.Scan(
			&i.GeckoID,
			&i.Url,
			&i.Caption,
			&i.DisplayOrder,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
