// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountAdmins(ctx context.Context) (int64, error)
	CountWaitlistEntries(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error)
	CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error)
	GetAdminByEmail(ctx context.Context, lower string) (AdminUser, error)
	GetAdminByID(ctx context.Context, id int32) (AdminUser, error)
	ListWaitlistEntries(ctx context.Context, arg ListWaitlistEntriesParams) ([]WaitlistEntry, error)
}

var _ Querier = (*Queries)(nil)
