// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAdmins(ctx context.Context) (int64, error)
	CountGeckos(ctx context.Context) (int64, error)
	CountGeckosByStatus(ctx context.Context) ([]CountGeckosByStatusRow, error)
	CountMediaForGecko(ctx context.Context, geckoID pgtype.Int4) (int64, error)
	CountWaitlistEntries(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error)
	CreateGecko(ctx context.Context, arg CreateGeckoParams) (Gecko, error)
	CreateGeckoGene(ctx context.Context, arg CreateGeckoGeneParams) (GeckoGene, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateSpecies(ctx context.Context, arg CreateSpeciesParams) (Species, error)
	CreateTrait(ctx context.Context, arg CreateTraitParams) (GeneticDictionary, error)
	CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error)
	DeleteGecko(ctx context.Context, id int32) error
	DeleteGenesForGecko(ctx context.Context, geckoID int32) error
	DeleteMedia(ctx context.Context, id int32) error
	GetAdminByEmail(ctx context.Context, lower string) (AdminUser, error)
	GetAdminByID(ctx context.Context, id int32) (AdminUser, error)
	GetCoverForGecko(ctx context.Context, geckoID pgtype.Int4) (Medium, error)
	GetGeckoByCode(ctx context.Context, code string) (GetGeckoByCodeRow, error)
	GetGeckoByID(ctx context.Context, id int32) (GetGeckoByIDRow, error)
	GetMediaByID(ctx context.Context, id int32) (Medium, error)
	GetSpeciesByCode(ctx context.Context, code SpeciesCode) (Species, error)
	GetSpeciesByID(ctx context.Context, id int32) (Species, error)
	GetTraitByNameAndSpecies(ctx context.Context, arg GetTraitByNameAndSpeciesParams) (GeneticDictionary, error)
	ListGeckoGenes(ctx context.Context) ([]ListGeckoGenesRow, error)
	ListGeckos(ctx context.Context) ([]ListGeckosRow, error)
	ListGenesForGecko(ctx context.Context, geckoID int32) ([]ListGenesForGeckoRow, error)
	ListMediaForGecko(ctx context.Context, geckoID pgtype.Int4) ([]Medium, error)
	ListSpecies(ctx context.Context) ([]Species, error)
	ListTraits(ctx context.Context) ([]GeneticDictionary, error)
	ListTraitsBySpecies(ctx context.Context, speciesID int32) ([]GeneticDictionary, error)
	ListWaitlistEntries(ctx context.Context, arg ListWaitlistEntriesParams) ([]WaitlistEntry, error)
	// $1 is the LIKE pattern, e.g. 'ZGLP-2026-%'. NULLIF guards against
	// legacy codes that don't have a 3rd segment (SPLIT_PART returns '').
	NextGeckoSequenceForSpeciesYear(ctx context.Context, code string) (int32, error)
	UpdateGecko(ctx context.Context, arg UpdateGeckoParams) (Gecko, error)
}

var _ Querier = (*Queries)(nil)
