// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: species.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecies = `-- name: CreateSpecies :one
INSERT INTO species (code, common_name, scientific_name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, code, common_name, scientific_name, description, created_at, updated_at
`

type CreateSpeciesParams struct {
	Code           SpeciesCode `json:"code"`
	CommonName     string      `json:"common_name"`
	ScientificName pgtype.Text `json:"scientific_name"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreateSpecies(ctx context.Context, arg CreateSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, createSpecies,
		arg.Code,
		arg.CommonName,
		arg.ScientificName,
		arg.Description,
	)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CommonName,
		&i.ScientificName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpeciesByCode = `-- name: GetSpeciesByCode :one
SELECT id, code, common_name, scientific_name, description, created_at, updated_at
FROM species
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetSpeciesByCode(ctx context.Context, code SpeciesCode) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByCode, code)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CommonName,
		&i.ScientificName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpeciesByID = `-- name: GetSpeciesByID :one
SELECT id, code, common_name, scientific_name, description, created_at, updated_at
FROM species
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSpeciesByID(ctx context.Context, id int32) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByID, id)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CommonName,
		&i.ScientificName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpecies = `-- name: ListSpecies :many
SELECT id, code, common_name, scientific_name, description, created_at, updated_at
FROM species
ORDER BY common_name
`

func (q *Queries) ListSpecies(ctx context.Context) ([]Species, error) {
	rows, err := q.db.Query(ctx, listSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Species{}
	for rows.Next() {
		var i Species
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CommonName,
			&i.ScientificName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
