// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: waitlist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWaitlistEntries = `-- name: CountWaitlistEntries :one
SELECT COUNT(*) FROM waitlist_entries
`

func (q *Queries) CountWaitlistEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist_entries (email, telegram, phone, interested_in, source, notes)
VALUES ($1, $2, $3, $4, COALESCE($5, 'website'), $6)
RETURNING id, email, telegram, phone, interested_in, source, notes, contacted_at, created_at, updated_at
`

type CreateWaitlistEntryParams struct {
	Email        string      `json:"email"`
	Telegram     pgtype.Text `json:"telegram"`
	Phone        pgtype.Text `json:"phone"`
	InterestedIn pgtype.Text `json:"interested_in"`
	Column5      interface{} `json:"column_5"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, createWaitlistEntry,
		arg.Email,
		arg.Telegram,
		arg.Phone,
		arg.InterestedIn,
		arg.Column5,
		arg.Notes,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Telegram,
		&i.Phone,
		&i.InterestedIn,
		&i.Source,
		&i.Notes,
		&i.ContactedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWaitlistEntries = `-- name: ListWaitlistEntries :many
SELECT id, email, telegram, phone, interested_in, source, notes, contacted_at, created_at, updated_at
FROM waitlist_entries
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWaitlistEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWaitlistEntries(ctx context.Context, arg ListWaitlistEntriesParams) ([]WaitlistEntry, error) {
	rows, err := q.db.Query(ctx, listWaitlistEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaitlistEntry{}
	for rows.Next() {
		var i WaitlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Telegram,
			&i.Phone,
			&i.InterestedIn,
			&i.Source,
			&i.Notes,
			&i.ContactedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
